const PERMISSIONS = require('./permissions');

const ROLE_PERMISSIONS = {
  ADMINISTRATOR: Object.values(PERMISSIONS),

  MANAGER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.EMPLOYEE_VIEW,
    PERMISSIONS.EMPLOYEE_CREATE,
    PERMISSIONS.EMPLOYEE_EDIT,
    PERMISSIONS.EMPLOYEE_IMPORT,
    PERMISSIONS.EMPLOYEE_EXPORT,

    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_CREATE,
    PERMISSIONS.ASSET_EDIT,
    PERMISSIONS.ASSET_IMPORT,
    PERMISSIONS.ASSET_EXPORT,

    PERMISSIONS.ASSIGNMENT_VIEW,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_RETURN,

    PERMISSIONS.REPORT_VIEW,
    PERMISSIONS.REPORT_EXPORT,

    PERMISSIONS.DEPARTMENT_VIEW,
    PERMISSIONS.LOCATION_VIEW,

    PERMISSIONS.ACTIVITY_VIEW,
  ],

  ENGINEER: [
    PERMISSIONS.DASHBOARD_VIEW,

    PERMISSIONS.EMPLOYEE_VIEW,

    PERMISSIONS.ASSET_VIEW,
    PERMISSIONS.ASSET_EDIT,

    PERMISSIONS.ASSIGNMENT_VIEW,
    PERMISSIONS.ASSIGNMENT_CREATE,
    PERMISSIONS.ASSIGNMENT_RETURN,

    PERMISSIONS.REPORT_VIEW,
  ],
};

module.exports = ROLE_PERMISSIONS;
